{{/*
Expand the name of the chart.
*/}}
{{- define "kopia.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "kopia.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{- define "kopia.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "kopia.labels" -}}
helm.sh/chart: {{ include "kopia.chart" . }}
{{ include "kopia.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.commonLabels }}
{{ toYaml . }}
{{- end }}
{{- end }}

{{/*
Selector labels.

A CronJob's jobTemplate selector is generated by the controller, so these are
not load-bearing the way a Deployment's are — but the NetworkPolicy podSelector
matches on them, so commonLabels still stays out.
*/}}
{{- define "kopia.selectorLabels" -}}
app.kubernetes.io/name: {{ include "kopia.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{- define "kopia.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "kopia.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{- define "kopia.image" -}}
{{- if .Values.image.digest -}}
{{- printf "%s@%s" .Values.image.repository .Values.image.digest -}}
{{- else -}}
{{- printf "%s:%s" .Values.image.repository (.Values.image.tag | default .Chart.AppVersion) -}}
{{- end -}}
{{- end }}

{{/*
State PVC name — config file plus content/metadata cache.

Same three cases as everywhere else in these charts:
  existingClaim  a volume this chart does NOT manage — mounted only
  claimName      a volume this chart DOES manage, under a name you choose
  neither        <fullname>-state
*/}}
{{- define "kopia.stateClaimName" -}}
{{- $p := .Values.persistence.state -}}
{{- if $p.existingClaim -}}
{{- $p.existingClaim -}}
{{- else -}}
{{- $p.claimName | default (printf "%s-state" (include "kopia.fullname" .)) -}}
{{- end -}}
{{- end }}

{{/*
Snapshot identity.

This is the single most important thing the chart does. Kopia files every
snapshot under "username@hostname:path", and every Job creates a pod with a
fresh random name — so without an override, last night's snapshot and tonight's
belong to two different sources. Retention is per source, so nothing would ever
be pruned, policies would apply to a source that never comes back, and the
snapshot list would grow one dead entry per night.
*/}}
{{- define "kopia.identityHostname" -}}
{{- .Values.identity.hostname | default (include "kopia.fullname" .) -}}
{{- end }}

{{- define "kopia.identityUsername" -}}
{{- .Values.identity.username | default "kopia" -}}
{{- end }}

{{/*
Component labels.

The chart renders two different workloads - the backup CronJob and the
optional read-only UI - and they must be distinguishable. Without this the
NetworkPolicy podSelector would match both, and a deny-all ingress rule meant
for the backup pod would also block the Ingress controller from reaching the
UI.
*/}}
{{- define "kopia.componentLabels" -}}
{{- include "kopia.selectorLabels" .ctx }}
app.kubernetes.io/component: {{ .component }}
{{- end }}

{{/*
Mode.

  cronjob  a CronJob takes the snapshots; the UI, if enabled at all, is a
           read-only window onto the repository.
  server   one long-running `kopia server`, writable, with the source tree
           mounted. Sources, schedules and policies are all managed in the
           browser - the Windows/KopiaUI experience. No CronJob.

Almost everything below branches on this, so read it as: the Deployment is the
backup client in server mode, and a bystander in cronjob mode.
*/}}
{{- define "kopia.isServerMode" -}}
{{- eq .Values.mode "server" -}}
{{- end }}

{{/*
Is a kopia server Deployment rendered at all?
*/}}
{{- define "kopia.serverEnabled" -}}
{{- if or (eq .Values.mode "server") .Values.ui.enabled -}}true{{- end -}}
{{- end }}

{{/*
Server connection is writable in server mode - it has to be, it is the thing
taking the snapshots. ui.readOnly only applies to the read-only window.
*/}}
{{- define "kopia.serverReadOnly" -}}
{{- if eq .Values.mode "server" -}}{{- else -}}{{- if .Values.ui.readOnly -}}true{{- end -}}{{- end -}}
{{- end }}

{{/*
In server mode the Deployment IS the backup client, so it carries the main
identity and the main state volume. In cronjob mode it is a second client and
gets its own of each.
*/}}
{{- define "kopia.serverIdentityHostname" -}}
{{- if eq .Values.mode "server" -}}
{{- include "kopia.identityHostname" . -}}
{{- else -}}
{{- include "kopia.uiIdentityHostname" . -}}
{{- end -}}
{{- end }}

{{- define "kopia.serverIdentityUsername" -}}
{{- if eq .Values.mode "server" -}}
{{- include "kopia.identityUsername" . -}}
{{- else -}}
{{- include "kopia.uiIdentityUsername" . -}}
{{- end -}}
{{- end }}

{{- define "kopia.serverStateEnabled" -}}
{{- if eq .Values.mode "server" -}}
{{- if .Values.persistence.state.enabled -}}true{{- end -}}
{{- else -}}
{{- if .Values.ui.persistence.cache.enabled -}}true{{- end -}}
{{- end -}}
{{- end }}

{{- define "kopia.serverStateClaimName" -}}
{{- if eq .Values.mode "server" -}}
{{- include "kopia.stateClaimName" . -}}
{{- else -}}
{{- include "kopia.uiCacheClaimName" . -}}
{{- end -}}
{{- end }}

{{- define "kopia.serverContentCacheMB" -}}
{{- if eq .Values.mode "server" -}}{{ .Values.cache.contentCacheSizeMB }}{{- else -}}{{ .Values.ui.cache.contentCacheSizeMB }}{{- end -}}
{{- end }}

{{- define "kopia.serverMetadataCacheMB" -}}
{{- if eq .Values.mode "server" -}}{{ .Values.cache.metadataCacheSizeMB }}{{- else -}}{{ .Values.ui.cache.metadataCacheSizeMB }}{{- end -}}
{{- end }}

{{/*
UI names and identity.
*/}}
{{/*
The SSH key is only mountable when a Secret was given at all.
*/}}
{{- define "kopia.sshEnabled" -}}
{{- if and .Values.auth.existingSecret .Values.auth.keys.sshPrivateKey -}}true{{- end -}}
{{- end }}

{{- define "kopia.uiFullname" -}}
{{- printf "%s-ui" (include "kopia.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{- define "kopia.uiCacheClaimName" -}}
{{- $p := .Values.ui.persistence.cache -}}
{{- if $p.existingClaim -}}
{{- $p.existingClaim -}}
{{- else -}}
{{- $p.claimName | default (printf "%s-cache" (include "kopia.uiFullname" .)) -}}
{{- end -}}
{{- end }}

{{/*
The UI connects under the SAME identity as the backup by default.

Kopia's snapshot view is organised by source, so matching the identity is what
makes the UI open on the sources this release actually backs up rather than an
empty list. It is safe because the server runs with --readonly and cannot
write a snapshot of its own; override it if you would rather keep the two
connections visibly separate.
*/}}
{{- define "kopia.uiIdentityHostname" -}}
{{- .Values.ui.identity.hostname | default (include "kopia.identityHostname" .) -}}
{{- end }}

{{- define "kopia.uiIdentityUsername" -}}
{{- .Values.ui.identity.username | default (include "kopia.identityUsername" .) -}}
{{- end }}

{{- define "kopia.uiConnectionFingerprint" -}}
{{- $parts := list
      .Values.sftp.host
      (.Values.sftp.port | toString)
      .Values.sftp.username
      .Values.sftp.path
      (include "kopia.serverIdentityHostname" .)
      (include "kopia.serverIdentityUsername" .)
      (include "kopia.serverReadOnly" .)
      (include "kopia.serverContentCacheMB" .)
      (include "kopia.serverMetadataCacheMB" .)
-}}
{{- join "|" $parts | sha256sum -}}
{{- end }}

{{/*
Mount path for one source. Defaults to /sources/<name>.
*/}}
{{- define "kopia.sourceMountPath" -}}
{{- .src.mountPath | default (printf "/sources/%s" .src.name) -}}
{{- end }}

{{/*
Every path handed to `kopia snapshot create`, as a list.

Explicit snapshotPaths wins; otherwise one entry per source. Setting it by hand
is how you snapshot a subdirectory of a mount, or something that arrived
through extraVolumes.
*/}}
{{- define "kopia.snapshotPaths" -}}
{{- $paths := list -}}
{{- if .Values.snapshotPaths -}}
{{- $paths = .Values.snapshotPaths -}}
{{- else -}}
{{- range $src := .Values.sources -}}
{{- $paths = append $paths (include "kopia.sourceMountPath" (dict "src" $src)) -}}
{{- end -}}
{{- end -}}
{{- toJson $paths -}}
{{- end }}

{{/*
Fingerprint of everything that goes into `kopia repository connect`.

The connection lives in a config file on the state volume and survives every
run — which means changing sftp.host in values would otherwise be silently
ignored forever. The script compares this against the stored copy and
reconnects when they differ.
*/}}
{{- define "kopia.connectionFingerprint" -}}
{{- $parts := list
      .Values.sftp.host
      (.Values.sftp.port | toString)
      .Values.sftp.username
      .Values.sftp.path
      (include "kopia.identityHostname" .)
      (include "kopia.identityUsername" .)
      (.Values.cache.contentCacheSizeMB | toString)
      (.Values.cache.metadataCacheSizeMB | toString)
      (.Values.auth.keys.sshPrivateKey | toString)
      (.Values.auth.keys.knownHosts | toString)
      (.Values.auth.keys.sftpPassword | toString)
-}}
{{- join "|" $parts | sha256sum -}}
{{- end }}

{{/*
Volumes and mounts shared by the CronJob pod.

state    config file + content/metadata cache (PVC, or emptyDir if disabled)
ssh      private key and known_hosts, projected 0400 out of the auth Secret
tmp      kopia's scratch space and log directory; readOnlyRootFilesystem needs it
sources  one per entry in .Values.sources, always read-only
*/}}
{{- define "kopia.volumes" -}}
- name: state
  {{- if .Values.persistence.state.enabled }}
  persistentVolumeClaim:
    claimName: {{ include "kopia.stateClaimName" . | quote }}
  {{- else }}
  emptyDir: {}
  {{- end }}
- name: tmp
  emptyDir: {}
{{- if include "kopia.sshEnabled" . }}
- name: ssh
  secret:
    secretName: {{ .Values.auth.existingSecret | quote }}
    {{- /*
      Project only the two SSH keys. Mounting the whole Secret would put
      KOPIA_PASSWORD on disk next to them for no reason.

      0444, not 0400: a projected Secret is owned by root:fsGroup, so 0400
      would be readable only by root while the container runs as
      podSecurityContext.runAsUser. Nothing outside this pod can see the
      tmpfs either way, and kopia's SSH client - unlike OpenSSH - does not
      refuse a key for being group-readable.
    */}}
    defaultMode: 0444
    items:
      - key: {{ .Values.auth.keys.sshPrivateKey }}
        path: id_key
      {{- if .Values.auth.keys.knownHosts }}
      - key: {{ .Values.auth.keys.knownHosts }}
        path: known_hosts
      {{- end }}
{{- end }}
{{- range $src := .Values.sources }}
- name: src-{{ $src.name }}
  {{- if eq ($src.type | default "hostPath") "hostPath" }}
  hostPath:
    path: {{ $src.hostPath | quote }}
    {{- /*
      Directory, not DirectoryOrCreate: an auto-created empty directory would
      make kopia record an empty snapshot as a success, and retention would then
      start pruning the snapshots that held real data.
    */}}
    type: {{ $src.hostPathType | default "Directory" }}
  {{- else }}
  persistentVolumeClaim:
    claimName: {{ $src.existingClaim | quote }}
    readOnly: true
  {{- end }}
{{- end }}
{{- with .Values.extraVolumes }}
{{- toYaml . }}
{{- end }}
{{- end }}

{{- define "kopia.volumeMounts" -}}
- name: state
  mountPath: {{ .Values.stateDir | quote }}
- name: tmp
  mountPath: /tmp
{{- if include "kopia.sshEnabled" . }}
- name: ssh
  mountPath: /kopia-ssh
  readOnly: true
{{- end }}
{{- range $src := .Values.sources }}
- name: src-{{ $src.name }}
  mountPath: {{ include "kopia.sourceMountPath" (dict "src" $src) | quote }}
  {{- with $src.subPath }}
  subPath: {{ . }}
  {{- end }}
  {{- /* Never writable. Kopia only reads, and a read-only mount removes a
         whole class of accidents. */}}
  readOnly: true
{{- end }}
{{- with .Values.extraVolumeMounts }}
{{- toYaml . }}
{{- end }}
{{- end }}

{{/*
Environment.

KOPIA_* names below are read by kopia itself. Everything the chart's own script
needs is prefixed CHART_ instead: kopia derives environment variable names from
its flags automatically, so an invented KOPIA_SOMETHING could silently become a
flag default.
*/}}
{{- define "kopia.env" -}}
{{- $state := .Values.stateDir -}}
- name: KOPIA_CONFIG_PATH
  value: {{ printf "%s/config/repository.config" $state | quote }}
- name: KOPIA_CACHE_DIRECTORY
  value: {{ printf "%s/cache" $state | quote }}
{{- /* Logs go to the emptyDir, not the state volume: they are per-run debris
       and would otherwise grow the PVC without bound. */}}
- name: KOPIA_LOG_DIR
  value: "/tmp/kopia-logs"
- name: KOPIA_CHECK_FOR_UPDATES
  value: "false"
{{- /*
  Nothing should resolve a path relative to HOME - config, cache and logs are
  all set above - but the root filesystem is read-only and there is no passwd
  entry for runAsUser, so point it somewhere writable rather than find out.
*/}}
- name: HOME
  value: "/tmp"
- name: KOPIA_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ .Values.auth.existingSecret }}
      key: {{ .Values.auth.keys.password }}
{{- if .Values.auth.keys.sftpPassword }}
- name: CHART_SFTP_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ .Values.auth.existingSecret }}
      key: {{ .Values.auth.keys.sftpPassword }}
{{- end }}
{{- range $name, $value := (.Values.env | default dict) }}
- name: {{ $name }}
  value: {{ $value | quote }}
{{- end }}
{{- with .Values.extraEnv }}
{{ toYaml . }}
{{- end }}
{{- end }}

{{/*
Validation.

Everything here is a misconfiguration that would otherwise show up as a failed
Job at 03:00, or — worse — as a Job that succeeds while backing up nothing.
*/}}
{{- define "kopia.validate" -}}

{{- if .Values.repository.configureInUI }}
{{- if ne .Values.mode "server" }}
{{- fail "repository.configureInUI needs mode=server: there is no browser to configure anything in when a CronJob does the work." }}
{{- end }}
{{- if .Values.verify.enabled }}
{{- fail "verify.enabled cannot work with repository.configureInUI: the verification Job connects from values, and there is nothing in values to connect with. Turn it on once the repository is configured." }}
{{- end }}
{{- else }}
{{- if not .Values.auth.existingSecret }}
{{- fail "auth.existingSecret is required: kopia cannot open a repository without its password. Create the Secret first, or set repository.configureInUI=true to do the whole setup in the browser." }}
{{- end }}
{{- if not .Values.auth.keys.password }}
{{- fail "auth.keys.password is required: it names the key inside auth.existingSecret that holds the repository password." }}
{{- end }}

{{- if not .Values.sftp.host }}
{{- fail "sftp.host is required (or set repository.configureInUI=true)" }}
{{- end }}
{{- if not .Values.sftp.username }}
{{- fail "sftp.username is required (or set repository.configureInUI=true)" }}
{{- end }}
{{- if not .Values.sftp.path }}
{{- fail "sftp.path is required: the absolute path of the repository directory on the SFTP server (or set repository.configureInUI=true)" }}
{{- end }}
{{- end }}

{{- /*
  Kopia verifies the server host key and has no "just trust it" switch, so key
  auth without known_hosts fails on every single run.
*/}}
{{- if and .Values.auth.keys.sshPrivateKey (not .Values.auth.keys.knownHosts) }}
{{- fail "auth.keys.knownHosts is required alongside auth.keys.sshPrivateKey: kopia verifies the SFTP host key and cannot be told to skip it. Generate it with: ssh-keyscan -p <port> <host>" }}
{{- end }}
{{- if and (not .Values.repository.configureInUI) (not .Values.auth.keys.sshPrivateKey) (not .Values.auth.keys.sftpPassword) }}
{{- fail "no SFTP credentials: set auth.keys.sshPrivateKey (recommended) or auth.keys.sftpPassword to a key in auth.existingSecret" }}
{{- end }}

{{- /*
  A backup of nothing is the failure this chart exists to prevent, so refuse to
  render rather than schedule a Job that snapshots an empty list.
*/}}
{{- /*
  In cronjob mode this is fatal: the Job would run `kopia snapshot create` with
  no paths and fail every night.

  In server mode it is legitimate - a server with no sources mounted is a
  browse-and-restore console for a repository something else fills. It cannot
  back anything up, so NOTES says so loudly rather than the chart refusing to
  render.
*/}}
{{- if and (not .Values.sources) (not .Values.snapshotPaths) (ne .Values.mode "server") }}
{{- fail "nothing to back up: set at least one entry under sources (or snapshotPaths, if the data arrives through extraVolumes)" }}
{{- end }}

{{- $seen := dict }}
{{- range $i, $src := .Values.sources }}
{{- if not $src.name }}
{{- fail (printf "sources[%d].name is required; it becomes the volume name and the default mount path" $i) }}
{{- end }}
{{- if not (regexMatch "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$" $src.name) }}
{{- fail (printf "sources[%d].name %q must be lowercase alphanumeric with dashes: it is used as a Kubernetes volume name" $i $src.name) }}
{{- end }}
{{- if hasKey $seen $src.name }}
{{- fail (printf "sources[%d].name %q is used twice" $i $src.name) }}
{{- end }}
{{- $_ := set $seen $src.name true }}
{{- $type := $src.type | default "hostPath" }}
{{- if not (has $type (list "hostPath" "pvc")) }}
{{- fail (printf "sources[%d].type must be \"hostPath\" or \"pvc\", got %q" $i $type) }}
{{- end }}
{{- if and (eq $type "hostPath") (not $src.hostPath) }}
{{- fail (printf "sources[%d].hostPath must be set when type is hostPath" $i) }}
{{- end }}
{{- /*
  The chart deliberately does not create source PVCs: you back up data that
  already exists somewhere, and a chart-managed claim would start empty.
*/}}
{{- if and (eq $type "pvc") (not $src.existingClaim) }}
{{- fail (printf "sources[%d].existingClaim must be set when type is pvc. This chart never creates a source claim — an empty one would produce an empty snapshot recorded as a success." $i) }}
{{- end }}
{{- end }}

{{- /*
  A Deployment selector is immutable and is built from these three keys. Let a
  commonLabel or podLabel override one and the pod template stops matching the
  selector: the Deployment then creates pods it cannot see, forever, and
  nothing in the event log says why.
*/}}
{{- $reserved := list "app.kubernetes.io/name" "app.kubernetes.io/instance" "app.kubernetes.io/component" }}
{{- range $src := list "commonLabels" "podLabels" }}
{{- range $k, $v := (index $.Values $src | default dict) }}
{{- if has $k $reserved }}
{{- fail (printf "%s.%q is a selector label. Overriding it leaves the Deployment unable to match its own pods - it would create them endlessly. Use a different key." $src $k) }}
{{- end }}
{{- end }}
{{- end }}

{{- /*
  Mount paths must be unique within a container, and the chart already occupies
  several. All of this rendered happily before and was then rejected by the API
  server with a message that named a volume, not the value that produced it.
*/}}
{{- $taken := dict
      .Values.stateDir "stateDir"
      "/scripts" "the generated scripts"
      "/tmp" "kopia's scratch space and log directory"
      "/kopia-ssh" "the SSH key and known_hosts"
      "/kopia-tls" "the UI certificate"
}}
{{- range $i, $src := .Values.sources }}
{{- $mp := include "kopia.sourceMountPath" (dict "src" $src) }}
{{- if hasKey $taken $mp }}
{{- fail (printf "sources[%d] mounts at %s, which is already used by %s. Set sources[%d].mountPath to something else." $i $mp (index $taken $mp) $i) }}
{{- end }}
{{- $_ := set $taken $mp (printf "sources[%d] (%s)" $i $src.name) }}
{{- /*
  The volume is named src-<name>, and a Kubernetes volume name is capped at 63
  characters.
*/}}
{{- if gt (len $src.name) 59 }}
{{- fail (printf "sources[%d].name is %d characters; the volume it produces (src-%s) would exceed the 63-character limit. Use 59 or fewer." $i (len $src.name) $src.name) }}
{{- end }}
{{- end }}
{{- if .Values.restore.enabled }}
{{- if hasKey $taken .Values.restore.mountPath }}
{{- fail (printf "restore.mountPath is %s, which is already used by %s. A restore target must be its own path - it is the only writable mount, and everything else is deliberately read-only." .Values.restore.mountPath (index $taken .Values.restore.mountPath)) }}
{{- end }}
{{- end }}

{{- /*
  hostPath does not follow the pod. If the Job lands on another node, type
  Directory stops it outright — which is the good outcome, but only because it
  turns a silent empty backup into a visible failure. Pin it properly.
*/}}
{{- $hasHostPath := false }}
{{- range $src := .Values.sources }}
{{- if eq ($src.type | default "hostPath") "hostPath" }}
{{- $hasHostPath = true }}
{{- end }}
{{- end }}
{{- if and $hasHostPath (not .Values.nodeSelector) (not .Values.affinity) }}
{{- fail "a source uses hostPath, so the Job must be pinned to the node holding the data: set nodeSelector (e.g. kubernetes.io/hostname: <node>) or affinity" }}
{{- end }}

{{- if not .Values.schedule }}
{{- fail "schedule is required (standard cron syntax, e.g. \"17 3 * * *\")" }}
{{- end }}

{{- /*
  Forbid is the only safe policy while the state volume is a single
  ReadWriteOnce claim: two kopia processes sharing one cache directory is
  undefined, and on the same node ReadWriteOnce does not stop them — access
  modes are enforced per node, not per pod.
*/}}
{{- if and (eq .Values.mode "cronjob") (ne .Values.concurrencyPolicy "Forbid") .Values.persistence.state.enabled }}
{{- fail "concurrencyPolicy must be Forbid while persistence.state is enabled: overlapping runs would share one cache directory and one repository config." }}
{{- end }}

{{- if .Values.verify.enabled }}
{{- if not .Values.verify.schedule }}
{{- fail "verify.schedule is required (standard cron syntax, e.g. \"23 5 * * 0\")" }}
{{- end }}
{{- /*
  0 is legitimate and useful: `kopia snapshot verify` still walks every
  snapshot and checks that every content it references exists. That is a full
  structural pass over the whole repository for the price of index downloads.
  The percentage only adds random file downloads on top, to catch bit rot.
*/}}
{{- $vp := .Values.verify.percent | float64 }}
{{- if or (lt $vp 0.0) (gt $vp 100.0) }}
{{- fail "verify.percent must be between 0 and 100" }}
{{- end }}
{{- if and .Values.verify.exportPath (not (or (hasPrefix "/tmp/" .Values.verify.exportPath) .Values.verify.extraVolumeMounts)) }}
{{- fail "verify.exportPath points outside /tmp with no writable mount: the root filesystem is read-only. Add verify.extraVolumes/extraVolumeMounts, or leave exportPath empty and read the dump from the Job log." }}
{{- end }}
{{- end }}

{{- if not (hasPrefix "/" .Values.stateDir) }}
{{- fail "stateDir must be an absolute path" }}
{{- end }}

{{- if .Values.restore.enabled }}
{{- if not (has .Values.restore.type (list "hostPath" "pvc")) }}
{{- fail (printf "restore.type must be \"hostPath\" or \"pvc\", got %q" .Values.restore.type) }}
{{- end }}
{{- if and (eq .Values.restore.type "hostPath") (not .Values.restore.hostPath) }}
{{- fail "restore.hostPath must be set when restore.type is hostPath" }}
{{- end }}
{{- if and (eq .Values.restore.type "pvc") (not .Values.restore.existingClaim) }}
{{- fail "restore.existingClaim must be set when restore.type is pvc. This chart never creates the restore claim." }}
{{- end }}
{{- if not (include "kopia.serverEnabled" .) }}
{{- fail "restore.enabled has no effect: only the kopia server pod restores anything. Set ui.enabled=true, or mode=server." }}
{{- end }}
{{- /*
  A hostPath restore target has to be on the node the server pod lands on. In
  server mode the pod inherits the top-level pinning; in cronjob mode it does
  not, so it needs its own.
*/}}
{{- if eq .Values.restore.type "hostPath" }}
{{- $pinned := or .Values.ui.nodeSelector .Values.ui.affinity }}
{{- if eq .Values.mode "server" }}
{{- $pinned = or $pinned .Values.nodeSelector .Values.affinity }}
{{- end }}
{{- if not $pinned }}
{{- fail "restore.type is hostPath, so the kopia server pod must be pinned to the node holding that directory: set ui.nodeSelector (e.g. kubernetes.io/hostname: <node>) or ui.affinity" }}
{{- end }}
{{- end }}
{{- end }}

{{- /*
  Several of these strings are embedded in the generated shell scripts inside
  double quotes, where $, ` and \ are still special. A path containing one of
  them would be silently expanded by the shell and kopia would receive a
  different value than you wrote - a wrong repository path is not something to
  discover from a backup that quietly went somewhere else.

  Spaces, colons, hashes and quotes are all fine; only these three are not.
*/}}
{{- $shellUnsafe := list "$" "`" "\\" }}
{{- $checked := dict
      "sftp.host" .Values.sftp.host
      "sftp.username" .Values.sftp.username
      "sftp.path" .Values.sftp.path
      "stateDir" .Values.stateDir
      "identity.hostname" .Values.identity.hostname
      "identity.username" .Values.identity.username
      "ui.identity.hostname" .Values.ui.identity.hostname
      "ui.identity.username" .Values.ui.identity.username
      "ui.auth.username" .Values.ui.auth.username
      "restore.mountPath" .Values.restore.mountPath
      "verify.exportPath" .Values.verify.exportPath
}}
{{- range $i, $src := .Values.sources }}
{{- $_ := set $checked (printf "sources[%d].hostPath" $i) ($src.hostPath | toString) }}
{{- $_ := set $checked (printf "sources[%d].mountPath" $i) (include "kopia.sourceMountPath" (dict "src" $src)) }}
{{- end }}
{{- range $p := .Values.snapshotPaths }}
{{- $_ := set $checked (printf "snapshotPaths %s" $p) $p }}
{{- end }}
{{- range $key, $val := $checked }}
{{- range $ch := $shellUnsafe }}
{{- if contains $ch ($val | toString) }}
{{- fail (printf "%s contains %q, which the shell would expand inside the generated script - kopia would receive a different value than you set. Rename the path." $key $ch) }}
{{- end }}
{{- end }}
{{- end }}

{{- if not (has .Values.mode (list "cronjob" "server")) }}
{{- fail (printf "mode must be \"cronjob\" or \"server\", got %q" .Values.mode) }}
{{- end }}

{{- if include "kopia.serverEnabled" . }}
{{- /*
  kopia server refuses to listen on a non-loopback address without a
  certificate, so one of the two has to be chosen deliberately.
*/}}
{{- if not (has .Values.ui.tls.mode (list "insecure" "existing")) }}
{{- fail "ui.tls.mode must be \"insecure\" (plain HTTP inside the cluster, TLS terminated at the Ingress) or \"existing\" (mount a cert Secret)" }}
{{- end }}
{{- if and (eq .Values.ui.tls.mode "existing") (not .Values.ui.tls.existingSecret) }}
{{- fail "ui.tls.existingSecret is required when ui.tls.mode is \"existing\": it must hold tls.crt and tls.key" }}
{{- end }}
{{- /*
  A writable server can delete snapshots. In server mode it must be writable -
  that is the whole point - so the acknowledgement is required either way.
*/}}
{{- if and (not (include "kopia.serverReadOnly" .)) (not .Values.ui.acknowledgeWritable) }}
{{- if eq .Values.mode "server" }}
{{- fail "mode=server runs a writable kopia server: it takes the snapshots, and it can also delete them. Set ui.acknowledgeWritable=true to confirm. (ui.readOnly is ignored in this mode.)" }}
{{- else }}
{{- fail "ui.readOnly=false lets the UI delete snapshots and take over maintenance ownership from the backup Job. Set ui.acknowledgeWritable=true if that is what you want." }}
{{- end }}
{{- end }}
{{- end }}

{{- if and .Values.ui.ingress.enabled (not (include "kopia.serverEnabled" .)) }}
{{- fail "ui.ingress.enabled has no effect: there is no server to expose. Set ui.enabled=true, or mode=server." }}
{{- end }}

{{- /*
  Server mode ignores several cronjob-only settings rather than half-applying
  them. Say so at render time instead of leaving someone to wonder why their
  schedule does nothing.
*/}}
{{- if eq .Values.mode "server" }}
{{- if .Values.snapshotPaths }}
{{- fail "snapshotPaths is a cronjob-mode setting. In server mode the snapshot sources are whatever you add in the UI; `sources` here only decides what the pod can see." }}
{{- end }}
{{- end }}

{{- end }}
