{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kopia.serviceAccountName" . }}
  labels:
    {{- include "kopia.labels" . | nindent 4 }}
  {{- $ann := merge (dict) (.Values.serviceAccount.annotations | default dict) (.Values.commonAnnotations | default dict) }}
  {{- with $ann }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
