apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "duplicati.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "duplicati.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "duplicati.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "duplicati.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "duplicati.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}

            {{- with .Values.envFromSecret }}
            - name: {{ .passwordEnvName | default "DUPLICATI__WEBSERVICE_PASSWORD" }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .passwordKey | default "DUPLICATI__WEBSERVICE_PASSWORD" }}

            - name: {{ .hostnamesEnvName | default "DUPLICATI__WEBSERVICE_ALLOWED_HOSTNAMES" }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .hostnamesKey | default "DUPLICATI__WEBSERVICE_ALLOWED_HOSTNAMES" }}

            - name: {{ .encryptionKeyEnvName | default "SETTINGS_ENCRYPTION_KEY" }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .encryptionKeyKey | default "SETTINGS_ENCRYPTION_KEY" }}

            - name: {{ .timezoneEnvName | default "DUPLICATI__WEBSERVICE_TIMEZONE" }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .timezoneKey | default "DUPLICATI__WEBSERVICE_TIMEZONE" }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if or .Values.persistence.config.enabled (eq .Values.persistence.config.type "hostPath") }}
            - name: config
              mountPath: /config
            {{- end }}
            {{- if or .Values.persistence.source.enabled .Values.persistence.source.existingClaim (eq .Values.persistence.source.type "hostPath") }}
            - name: source
              mountPath: /source
            {{- end }}
            {{- if or .Values.persistence.backups.enabled .Values.persistence.backups.existingClaim (eq .Values.persistence.backups.type "hostPath") }}
            - name: backups
              mountPath: /backups
            {{- end }}
      volumes:
        {{- /* Config volume */ -}}
        {{- if or .Values.persistence.config.enabled (eq .Values.persistence.config.type "hostPath") }}
        - name: config
          {{- if eq .Values.persistence.config.type "hostPath" }}
          hostPath:
            path: {{ .Values.persistence.config.hostPath }}
            type: DirectoryOrCreate
          {{- else }}
          persistentVolumeClaim:
            claimName: pvc-duplicati-config
          {{- end }}
        {{- end }}

        {{- /* Source volume */ -}}
        {{- if .Values.persistence.source.existingClaim }}
        - name: source
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.source.existingClaim }}
        {{- else if eq .Values.persistence.source.type "hostPath" }}
        - name: source
          hostPath:
            path: {{ .Values.persistence.source.hostPath }}
            type: DirectoryOrCreate
        {{- else if .Values.persistence.source.enabled }}
        - name: source
          persistentVolumeClaim:
            claimName: pvc-duplicati-source
        {{- end }}

        {{- /* Backups volume */ -}}
        {{- if .Values.persistence.backups.existingClaim }}
        - name: backups
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.backups.existingClaim }}
        {{- else if eq .Values.persistence.backups.type "hostPath" }}
        - name: backups
          hostPath:
            path: {{ .Values.persistence.backups.hostPath }}
            type: DirectoryOrCreate
        {{- else if .Values.persistence.backups.enabled }}
        - name: backups
          persistentVolumeClaim:
            claimName: pvc-duplicati-backups
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}