{{- if .Values.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-duplicati-config
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
  storageClassName: {{ .Values.persistence.config.storageClassName }}
---
{{- end }}

{{- if and .Values.persistence.source.enabled (not .Values.persistence.source.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-duplicati-source
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.source.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.source.size }}
  storageClassName: {{ .Values.persistence.source.storageClassName }}
---
{{- end }}

{{- if and .Values.persistence.backups.enabled (not .Values.persistence.backups.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-duplicati-backups
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.backups.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.backups.size }}
  storageClassName: {{ .Values.persistence.backups.storageClassName }}
---
{{- end }}
